service: appsync-masterclass-backend
frameworkVersion: '2'

plugins:
  - serverless-appsync-plugin

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

#package:
#  exclude:
#    - package-lock.json
#    - package.json

custom:
  appSync:
    - ${file(serverless.appsync-api.yml)}

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: false
            RequireNumbers: false
            RequireUppercase: false
            RequireSymbols: false
        UsernameAttributes:
          - email
        Schema:
          - AttributeDataType: String
            Name: name
            Required: false
            Mutable: true
    WebUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        UserPoolId: !Ref CognitoUserPool
        ClientName: web
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH # this is the default & recommended auth flow using the Secure Remote Password (SRP) protocol
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH # required and con NOT be disabled
        PreventUserExistenceErrors: ENABLED # so when someone tries to sign in through Cognito, but the user does not exist

  Outputs:
    CognitoUserPoolId:
      Value: !Ref CognitoUserPool