service: appsync-masterclass-backend

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1


resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequiredLowerCase: false
            RequiredNumbers: false
            RequiredUpperCase: false
            RequiredSymbols: false
        UsernameAttributes:
          - email
        Schema:
          - AttributeDataType: String
            Name: name
            Required: false
            Mutable: true
  Outputs:
    CognitoUserPoolId:
      Value: !Ref CognitoUserPool