service: appsync-masterclass-backend
frameworkVersion: '2'

plugins:
  - serverless-appsync-plugin

provider:
  name: aws
  #stage: dev # default stage is "dev" if none specified.
  runtime: nodejs12.x
  region: us-east-1

#package:
#  exclude:
#    - package-lock.json
#    - package.json

custom:
  # Convention is to define a stage under the "custom" section, where a stage override is checked for.
  #
  #
  # The following line of code states:
  #   Step1 -> listen to the command line for any "stage overrides".
  #   Step2 -> if no "stage overrides", then reference the "stage" property under the "provider" section above (*within this yml file).
  #
  # stage: ${listen-for-overrides, else-reference-stage-property-under-the-provider-section}
  stage: ${opt:stage, self:provider.stage}
  appSync:
    - ${file(serverless.appsync-api.yml)}

functions:
  confirmUserSignup:
    handler: functions/confirm-user-signup.handler
    environment:
      USERS_TABLE: !Ref UsersTable # environment variable sued to reference the Users Table in DynamoDB

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST # this places the DDB instance onto a onDemand billing cycle
        KeySchema:
          - AttributeName: id # specifying the hash key
            KeyType: HASH
        AttributeDefinitions: # defining attributes by "name:dataType" pairs
          - AttributeName: id
            AttributeType: S
        Tags: # adding tags is considered good practice
          - Key: Environment # this env tag will be useful to differentiate between dev, test, prod, etc.
            Value: ${self:custom.stage} # this variable syntax references a property named "stage", which is defined under the "custom" section.
          - Key: Name # we can use the "Name" tag for Cost Tracking within AWS billing.
            Value: users-tag

    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: false
            RequireNumbers: false
            RequireUppercase: false
            RequireSymbols: false
        UsernameAttributes:
          - email
        Schema:
          - AttributeDataType: String
            Name: name
            Required: false
            Mutable: true
    WebUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        UserPoolId: !Ref CognitoUserPool
        ClientName: web
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH # this is the default & recommended auth flow using the Secure Remote Password (SRP) protocol
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH # required and con NOT be disabled
        PreventUserExistenceErrors: ENABLED # so when someone tries to sign in through Cognito, but the user does not exist

  Outputs:
    CognitoUserPoolId:
      Value: !Ref CognitoUserPool